### ISSUE TITLE
request for rosbag file

### ISSUE THREAD

**Issue by adithyab94** [zhuge2333/4DRadarSLAM#4]
Hi, is it possible to push a sample rosbag file for trying out this. Just a few seconds of data would suffice and will be helpful.

Thank you

**Comment by junzhang2016** [comment]
Hi, in the readme, we have provided the link to all rosbags:
https://github.com/junzhang2016/NTU4DRadLM

**Comment by adithyab94** [comment]
Great. This will be helpful. Thank you very much
